In [216]:
!pip install sqlalchemy pymysql
from sqlalchemy import create_engine
import numpy as np
import pandas as pd
print('libraries imported successfully')

Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
libraries imported successfully

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [217]:
#inserting data inside the notebook
df=pd.read_csv('retail_store_sales (1).csv')
df.head(20)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False
10,TXN_8776416,CUST_22,Butchers,Item_3_BUT,8.0,9.0,72.0,Cash,In-store,2024-12-14,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
12,TXN_5874772,CUST_23,Food,Item_2_FOOD,6.5,7.0,45.5,Cash,Online,2023-09-09,True
13,TXN_4413070,CUST_14,Patisserie,Item_24_PAT,39.5,6.0,237.0,Digital Wallet,In-store,2022-05-20,False
14,TXN_2490363,CUST_09,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,NaN
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
16,TXN_7563311,CUST_23,Patisserie,Item_17_PAT,29.0,8.0,232.0,Cash,Online,2024-11-16,True
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
18,TXN_4396807,CUST_17,Electric household essentials,Item_13_EHE,23.0,1.0,23.0,Digital Wallet,In-store,2022-02-07,False
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False

In [218]:
#understanding the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [219]:
#exploring the data to check the mean,count,max,std
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [220]:
#checking the null values in the data
df.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [221]:
#cleaning the data
#check the duplicates and handle them
df.duplicated().sum()

0

In [222]:
#handling the null values column by column
df['Item'].isna().sum()
#handling the null values by dropping the entire column since it is not needed
df.drop(['Item'],axis=1,inplace=True)
print('column dropped since it is not required in this analysis')

column dropped since it is not required in this analysis

In [223]:
# checking missing values before filling
df['Price Per Unit'].isna().sum()

# fill missing values safely
df['Price Per Unit'] = df['Price Per Unit'].fillna(
    df['Total Spent'] / df['Quantity'].replace(0, pd.NA)
)

# checking missing values after filling
df['Price Per Unit'].isna().sum()

# checking invalid values
df[df['Price Per Unit'] <= 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Category, Price Per Unit, Quantity, Total Spent, Payment Method, Location, Transaction Date, Discount Applied]
Index: []

In [224]:
#handling null values for column Quantity
#checking te null values first
df['Quantity'].isna().sum()

# fill missing values safely
df['Quantity'] = df['Quantity'].fillna(
    df['Total Spent'] / df['Price Per Unit'].replace(0, pd.NA)
)

# checking missing values after filling
df['Quantity'].isna().sum()

# checking invalid values
df[df['Quantity'] <= 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Category, Price Per Unit, Quantity, Total Spent, Payment Method, Location, Transaction Date, Discount Applied]
Index: []

In [225]:
#dropping 2025 data since its incomplete data and the fact that that the data is having a big impact on the analysis outcome
df.drop([2025])

,Transaction ID,Customer ID,Category,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [226]:
#handling the total ampunt spent column
df['Total Spent']=df['Quantity']*df['Price Per Unit']

In [227]:
#handling null values for the column Discount Applied
df['Discount Applied']=df['Discount Applied'].fillna(pd.NA)

In [228]:
#Data validation
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

df = df[df['Transaction Date'].dt.year != 2025]

In [229]:
#handling columns
df.columns=(
    df.columns.str.strip()
    .str.replace(' ','_')
    .str.title()
    
)
df.columns

Index(['Transaction_Id', 'Customer_Id', 'Category', 'Price_Per_Unit',
       'Quantity', 'Total_Spent', 'Payment_Method', 'Location',
       'Transaction_Date', 'Discount_Applied'],
      dtype='object')

In [230]:
#handling the data types of the data
#handling numeric columns
numeric_columns=['Price_Per_Unit','Quantity', 'Total_Spent']
df[numeric_columns]=df[numeric_columns].apply(pd.to_numeric)
print('Numeric columns handled')

Numeric columns handled

In [231]:
#handling text columns
Text_Columns=['Transaction_Id', 'Customer_Id', 'Category','Payment_Method', 'Location','Discount_Applied']
df[Text_Columns]=df[Text_Columns].astype(str)
print('text columns handled')

text columns handled

In [232]:
#handling date columns
df['Transaction_Date']=pd.to_datetime(df['Transaction_Date'],format='%Y-%m-%d').dt.date
print('date columns handled')

date columns handled

In [233]:
#handle the null values for the column quantity with median
# handling the price column by filling null values with median
Quantity_Median = df['Quantity'].median()

df['Quantity'] = df['Quantity'].fillna(Quantity_Median)

In [234]:
#handling the price column by filling the null values with median

# handling the price column by filling null values with median
Price_Per_Unit_Median = df['Price_Per_Unit'].median()

df['Price_Per_Unit'] = df['Price_Per_Unit'].fillna(Price_Per_Unit_Median)

In [235]:
df['Total_Spent']=df['Quantity']*df['Price_Per_Unit']

In [236]:
df.columns

Index(['Transaction_Id', 'Customer_Id', 'Category', 'Price_Per_Unit',
       'Quantity', 'Total_Spent', 'Payment_Method', 'Location',
       'Transaction_Date', 'Discount_Applied'],
      dtype='object')

In [237]:
#handling outliers from the columns
Q1=df['Price_Per_Unit'].quantile(0.25)
Q3=df['Price_Per_Unit'].quantile(0.75)
IQ=Q3-Q1
LB=Q1-1.5*IQ
UP=Q3+1.5*IQ

Outliers=df[(df['Price_Per_Unit']<LB)|(df['Price_Per_Unit']>UP)]
print(Outliers)

Empty DataFrame
Columns: [Transaction_Id, Customer_Id, Category, Price_Per_Unit, Quantity, Total_Spent, Payment_Method, Location, Transaction_Date, Discount_Applied]
Index: []

In [238]:
#handling outliers from the columns
Q1=df['Quantity'].quantile(0.25)
Q3=df['Quantity'].quantile(0.75)
IQ=Q3-Q1
LB=Q1-1.5*IQ
UP=Q3+1.5*IQ

Outliers=df[(df['Quantity']<LB)|(df['Quantity']>UP)]
print(Outliers)

Empty DataFrame
Columns: [Transaction_Id, Customer_Id, Category, Price_Per_Unit, Quantity, Total_Spent, Payment_Method, Location, Transaction_Date, Discount_Applied]
Index: []

In [239]:
#creating an engine
engine=create_engine('mysql+pymysql://root:Terere#123@localhost/first_intership_project')

In [240]:
#transfering data from notebook to mysql
df.to_sql(name='first_intership_project',con=engine,if_exists='replace', index=False)

12362

In [241]:
#saving the data
df.to_csv('Cleaned_Data.csv',index=False)